namespace Cycliko.Invitation.Domain.Tests
{
    [TestClass]
    public class RaceModelUnitTest
    {
        [TestMethod]
        public void CreateRaceInvitation_ThenNumberIsAutoGenerated()
        {
            // Arrange
            var invitation = ArrangeInvitation();

            // Act
            var invitationNr = invitation.InvitationNr;

            // Assert
            Assert.IsFalse(string.IsNullOrWhiteSpace(invitationNr));

        }

        private RaceInvitation ArrangeInvitation()
        {
            var race = new RaceModel
            {
                RaceName = "Ronde van Vlaanderen",
                Description = "108e editie",
                Location = "Antwerpen - Oudenaarde"

            };

            return new RaceInvitation
            {
                RiderName = "Michal Kwiatkowski",
                RiderEmail = "kwiatek@cycliko.pl",
                RaceDetails = race,
                ExpectedEnergyKJ = 1000 * 35,
                RaceDistance = 270.8,
                RiderAddress = "Chelmza, Chelminska 1, Poland"
            };
        }
    }
}